/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

/**
 *
 * @author Guilherme
 */
public class TelaCadastroLivros extends javax.swing.JFrame {

    /**
     * Creates new form TelaCadastroLivros
     */
    public TelaCadastroLivros() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelCadastroLivros = new javax.swing.JPanel();
        jLabelNomeLivro = new javax.swing.JLabel();
        jTextFieldNomeLivro = new javax.swing.JTextField();
        jLabelTitulo = new javax.swing.JLabel();
        jTextFieldTituloLivro = new javax.swing.JTextField();
        jLabelAutorLivro = new javax.swing.JLabel();
        jTextFieldAutorLivro = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jTextFieldNotaLivro = new javax.swing.JTextField();
        jButtonSalvarLivro = new javax.swing.JButton();
        jButtonLimparLivro = new javax.swing.JButton();
        jButtonCancelarLivro = new javax.swing.JButton();
        jButtonConsultarLivro = new javax.swing.JButton();
        jLabelCadastroLivros = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Livraria");
        setResizable(false);

        jPanelCadastroLivros.setBackground(new java.awt.Color(102, 102, 102));
        jPanelCadastroLivros.setPreferredSize(new java.awt.Dimension(780, 400));

        jLabelNomeLivro.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        jLabelNomeLivro.setForeground(new java.awt.Color(255, 255, 255));
        jLabelNomeLivro.setText("Nome:");

        jTextFieldNomeLivro.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N

        jLabelTitulo.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        jLabelTitulo.setForeground(new java.awt.Color(255, 255, 255));
        jLabelTitulo.setText("Título:");

        jTextFieldTituloLivro.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N

        jLabelAutorLivro.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        jLabelAutorLivro.setForeground(new java.awt.Color(255, 255, 255));
        jLabelAutorLivro.setText("Autor:");

        jTextFieldAutorLivro.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N

        jLabel1.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Nota:");

        jTextFieldNotaLivro.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N

        jButtonSalvarLivro.setBackground(new java.awt.Color(240, 240, 240));
        jButtonSalvarLivro.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        jButtonSalvarLivro.setText("Salvar");

        jButtonLimparLivro.setBackground(new java.awt.Color(240, 240, 240));
        jButtonLimparLivro.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        jButtonLimparLivro.setText("Limpar");

        jButtonCancelarLivro.setBackground(new java.awt.Color(240, 240, 240));
        jButtonCancelarLivro.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        jButtonCancelarLivro.setText("Cancelar");

        jButtonConsultarLivro.setBackground(new java.awt.Color(240, 240, 240));
        jButtonConsultarLivro.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        jButtonConsultarLivro.setText("Consultar");

        javax.swing.GroupLayout jPanelCadastroLivrosLayout = new javax.swing.GroupLayout(jPanelCadastroLivros);
        jPanelCadastroLivros.setLayout(jPanelCadastroLivrosLayout);
        jPanelCadastroLivrosLayout.setHorizontalGroup(
            jPanelCadastroLivrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelCadastroLivrosLayout.createSequentialGroup()
                .addGroup(jPanelCadastroLivrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelCadastroLivrosLayout.createSequentialGroup()
                        .addGap(63, 63, 63)
                        .addGroup(jPanelCadastroLivrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelNomeLivro)
                            .addComponent(jLabelTitulo)
                            .addComponent(jLabelAutorLivro)
                            .addComponent(jLabel1))
                        .addGap(44, 44, 44)
                        .addGroup(jPanelCadastroLivrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanelCadastroLivrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jTextFieldNomeLivro, javax.swing.GroupLayout.DEFAULT_SIZE, 490, Short.MAX_VALUE)
                                .addComponent(jTextFieldTituloLivro)
                                .addComponent(jTextFieldAutorLivro))
                            .addComponent(jTextFieldNotaLivro, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanelCadastroLivrosLayout.createSequentialGroup()
                        .addGap(114, 114, 114)
                        .addComponent(jButtonSalvarLivro)
                        .addGap(18, 18, 18)
                        .addComponent(jButtonLimparLivro)
                        .addGap(18, 18, 18)
                        .addComponent(jButtonCancelarLivro)
                        .addGap(18, 18, 18)
                        .addComponent(jButtonConsultarLivro)))
                .addContainerGap(133, Short.MAX_VALUE))
        );
        jPanelCadastroLivrosLayout.setVerticalGroup(
            jPanelCadastroLivrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelCadastroLivrosLayout.createSequentialGroup()
                .addGap(58, 58, 58)
                .addGroup(jPanelCadastroLivrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelNomeLivro)
                    .addComponent(jTextFieldNomeLivro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanelCadastroLivrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelTitulo)
                    .addComponent(jTextFieldTituloLivro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanelCadastroLivrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelAutorLivro)
                    .addComponent(jTextFieldAutorLivro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanelCadastroLivrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jTextFieldNotaLivro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 93, Short.MAX_VALUE)
                .addGroup(jPanelCadastroLivrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonSalvarLivro)
                    .addComponent(jButtonLimparLivro)
                    .addComponent(jButtonCancelarLivro)
                    .addComponent(jButtonConsultarLivro))
                .addGap(73, 73, 73))
        );

        jLabelCadastroLivros.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jLabelCadastroLivros.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8-livros-64.png"))); // NOI18N
        jLabelCadastroLivros.setText("Cadastro de Livros");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanelCadastroLivros, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(270, 270, 270)
                .addComponent(jLabelCadastroLivros)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jLabelCadastroLivros)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanelCadastroLivros, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(60, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaCadastroLivros.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaCadastroLivros.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaCadastroLivros.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaCadastroLivros.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaCadastroLivros().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonCancelarLivro;
    private javax.swing.JButton jButtonConsultarLivro;
    private javax.swing.JButton jButtonLimparLivro;
    private javax.swing.JButton jButtonSalvarLivro;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabelAutorLivro;
    private javax.swing.JLabel jLabelCadastroLivros;
    private javax.swing.JLabel jLabelNomeLivro;
    private javax.swing.JLabel jLabelTitulo;
    private javax.swing.JPanel jPanelCadastroLivros;
    private javax.swing.JTextField jTextFieldAutorLivro;
    private javax.swing.JTextField jTextFieldNomeLivro;
    private javax.swing.JTextField jTextFieldNotaLivro;
    private javax.swing.JTextField jTextFieldTituloLivro;
    // End of variables declaration//GEN-END:variables
}
